name: My Blog
description: Personal Blog
meta_description: "My Blog, Personal blog"

markdown: kramdown
highlighter: pygments
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.mazkaaa.net/'
google_analytics: 'UA-73144591-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://blog.mazkaaa.net/'
author:         'Muhammad Azka'
